<?php

declare(strict_types=1);

namespace MichaelFrank\OpenRouter\Responses;

use MichaelFrank\OpenRouter\Enums\FinishReason;

/**
 * Class CompletionChoice
 *
 * A single choice item generated by a model completions run.
 *
 * @package MichaelFrank\OpenRouter\Responses
 */
final readonly class CompletionChoice
{
    /**
     * CompletionChoice constructor.
     *
     * @param int $index
     * @param ChatMessage $message
     * @param FinishReason|null $finishReason
     * @param string|null $nativeFinishReason
     * @param ChoiceError|null $error
     * @param array<string, mixed>|null $logprobs
     */
    public function __construct(
        public int $index,
        public ChatMessage $message,
        public ?FinishReason $finishReason,
        public ?string $nativeFinishReason,
        public ?ChoiceError $error,
        public ?array $logprobs,
    ) {
    }

    /**
     * Factory to build CompletionChoice from payload array.
     *
     * @param array<string, mixed> $data
     * @return self
     */
    public static function fromArray(array $data): self
    {
        $finish = $data['finish_reason'] ?? null;
        $native = $data['native_finish_reason'] ?? null;
        $index = $data['index'] ?? null;

        $messageArr = [];
        $messageData = $data['message'] ?? [];
        if (is_array($messageData)) {
            foreach ($messageData as $k => $v) {
                if (is_string($k)) {
                    $messageArr[$k] = $v;
                }
            }
        }

        $error = null;
        if (isset($data['error']) && is_array($data['error'])) {
            $errorArr = [];
            foreach ($data['error'] as $k => $v) {
                if (is_string($k)) {
                    $errorArr[$k] = $v;
                }
            }
            $error = ChoiceError::fromArray($errorArr);
        }

        $logprobs = null;
        if (isset($data['logprobs']) && is_array($data['logprobs'])) {
            $logprobs = [];
            foreach ($data['logprobs'] as $k => $v) {
                if (is_string($k)) {
                    $logprobs[$k] = $v;
                }
            }
        }

        return new self(
            index: is_numeric($index) ? (int)$index : 0,
            message: ChatMessage::fromArray($messageArr),
            finishReason: is_string($finish) ? FinishReason::fromString($finish) : null,
            nativeFinishReason: is_string($native) ? $native : null,
            error: $error,
            logprobs: $logprobs
        );
    }

    /**
     * Checks if this choice item is an error.
     *
     * @return bool
     */
    public function isError(): bool
    {
        return $this->error !== null;
    }
}
