<?php

declare(strict_types=1);

namespace MichaelFrank\OpenRouter\Responses;

use MichaelFrank\OpenRouter\Enums\ToolType;

/**
 * Class ToolCall
 *
 * Represents a tool call request generated by the model.
 *
 * @package MichaelFrank\OpenRouter\Responses
 */
final readonly class ToolCall
{
    /**
     * ToolCall constructor.
     *
     * @param string $id
     * @param ToolType $type
     * @param FunctionCall $function
     */
    public function __construct(
        public string $id,
        public ToolType $type,
        public FunctionCall $function,
    ) {
    }

    /**
     * Factory to build ToolCall from payload array.
     *
     * @param array<string, mixed> $data
     * @return self
     */
    public static function fromArray(array $data): self
    {
        $id = $data['id'] ?? null;
        $type = $data['type'] ?? null;
        $functionData = isset($data['function']) && is_array($data['function']) ? $data['function'] : [];

        return new self(
            id: is_string($id) ? $id : '',
            type: ToolType::fromString(is_string($type) ? $type : 'function'),
            function: FunctionCall::fromArray($functionData)
        );
    }
}
